version: '3.8'

services:
  moodle-tutorial:
    image: ghcr.io/andrevictor20/moodle-tutorial:latest
    container_name: moodle-tutorial
    ports:
      - "9800:3000"
    restart: unless-stopped

  # Watchtower monitora as imagens Docker e atualiza automaticamente (CD)
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_CLEANUP=true
    restart: unless-stopped
